"""Guided experiments: original teaching, explicitly stated physical models.
The calculations and SVG scenes live in assets/physics-labs.js. Existing quiz IDs
and studied-section IDs are independent of these demonstrations.
"""
LABS = {}
def lab(section, key, title, intro, assumptions, steps, predict):
    LABS.setdefault(section, []).append(dict(key=key,title=title,intro=intro,assumptions=assumptions,steps=steps,predict=predict))
def step(title, equation, text):
    return dict(title=title,equation=equation,text=text)
def prediction(question, options, answer, explanation):
    return dict(question=question,options=options,answer=answer,explanation=explanation)

lab('maths-calculus','tangent','A tangent becomes a velocity',
    'Bring two points together on a position–time curve. Watch an average velocity approach the instantaneous velocity at the chosen instant.',
    'Position x(t) = t² metres when t is measured in seconds; t ≥ 0. The coefficient of t² has units m/s². The time gap remains positive.',
    [step('Compare two positions',r'\bar v=\frac{x(t+\Delta t)-x(t)}{\Delta t}','The chord connects two measured positions. Its rise is a displacement; its run is a time interval.'),step('Expand the difference',r'\bar v=\frac{(t+\Delta t)^2-t^2}{\Delta t}=2t+\Delta t','Cancel the common position and divide each remaining term by the interval. Values here use SI units.'),step('Shrink the time interval',r'v=\lim_{\Delta t\to0}\bar v=2t','The chord approaches the tangent. Velocity is the slope at one instant, in m/s.')],
    prediction('As the positive time gap shrinks, the chord slope…',['approaches the tangent slope','always becomes zero'],0,'The gap tends to zero; the rate tends to the finite derivative 2t. A small time interval does not mean a small velocity.'))
lab('maths-integrals','integral','Build an integral from little areas',
    'Increase the number of rectangles under a force–position graph. The total approaches the work done by a changing force.',
    'F(x) = 2x with F in N and x in m; integrate from 0 to 4 m. Rectangles use left endpoints, so this increasing function is underestimated.',
    [step('One small displacement',r'\Delta W\approx F(x_i)\Delta x','A thin rectangle has height force and width displacement. Its area therefore has units N m = J.'),step('Add the rectangles',r'W_N=\sum_{i=0}^{N-1}F(x_i)\Delta x','Smaller widths follow the curve more closely. Left rectangles omit a little area for this increasing force.'),step('Take the continuous limit',r'W=\int_0^4 2x\,dx=[x^2]_0^4=16\ \mathrm{J}','Integration accounts for every small displacement. The area is also a triangle of base 4 m and height 8 N.')],
    prediction('For this increasing force, more left-endpoint rectangles make the estimate…',['rise toward 16 J','fall toward 0 J'],0,'Each refinement recovers some previously omitted area. This monotonic behaviour is specific to the increasing curve and left-endpoint rule.'))
lab('units-instruments','vernier','Read a vernier without guessing',
    'Move the jaw, identify the main-scale reading before the vernier zero, then find the line that coincides.',
    'Ideal direct vernier: 10 vernier divisions span 9 mm; 1 main division = 1 mm; least count = 0.1 mm; zero error is absent.',
    [step('Find the least count',r'\mathrm{LC}=1\ \mathrm{MSD}-1\ \mathrm{VSD}=1-0.9=0.1\ \mathrm{mm}','The small mismatch between the scales makes one line coincide for each tenth of a millimetre.'),step('Read the complete millimetres',r'\mathrm{MSR}=\lfloor L\rfloor\ \mathrm{mm}','Use the main-scale mark just before the vernier zero, rather than the closest mark.'),step('Add the coincidence',r'L=\mathrm{MSR}+n\,\mathrm{LC}','n is the coincident vernier division, counted from zero. A positive zero error would be subtracted from this observed reading.')],
    prediction('If a caliper reads +0.2 mm when closed, correct a measured reading by…',['subtracting 0.2 mm','adding 0.2 mm'],0,'Positive zero error makes every observed length too large, so the zero correction is negative.'))
lab('units-propagation','uncertainty','Why a radius error matters twice',
    'Compare a circle at the measured radius with its smallest and largest possible radii. Relate the exact area spread to the first-order estimate.',
    'A = πr²; nominal r = 10 cm. Slider gives a symmetric radius bound, not a confidence interval. The linear approximation is most accurate for small fractional errors.',
    [step('State the geometry',r'A=\pi r^2','Area contains the radius twice. The units are squared too: cm² here.'),step('Differentiate the dependence',r'dA=2\pi r\,dr','A small increase in radius adds a thin ring. Its area is approximately circumference times thickness.'),step('Divide by the original area',r'\frac{\Delta A}{A}\approx2\frac{\Delta r}{r}','The first-order fractional area uncertainty is twice the fractional radius uncertainty. Exact upper and lower bounds are slightly asymmetric.')],
    prediction('A 2% radius uncertainty gives approximately…',['4% area uncertainty','2% area uncertainty'],0,'The exponent of radius is 2. For the exact upper bound, (1.02)² − 1 = 4.04%, close to the first-order 4%.'))
lab('linear-equations','kinematics','One motion, three connected graphs',
    'Scrub time or play the cart. Read position, velocity, and acceleration together, including the instant when direction reverses.',
    'One-dimensional constant acceleration; x₀ = 0; positive is to the right; no boundaries or collisions. The track is rescaled to include the full trajectory.',
    [step('Acceleration changes velocity',r'v(t)=u+at','u is initial velocity (m/s), a is constant acceleration (m/s²), and t is elapsed time (s). The velocity graph has slope a.'),step('Velocity accumulates displacement',r'x(t)=ut+\frac12at^2','Position is the signed area under v(t). A negative area moves the cart toward decreasing x.'),step('Interpret the turning point',r't_{\rm turn}=-\frac ua\quad(a\ne0)','Only a turning time inside the observed interval matters. At that instant v = 0 but acceleration can remain nonzero.')],
    prediction('When velocity is negative and acceleration is positive, the cart initially…',['slows down','speeds up'],0,'Acceleration opposes the current velocity, reducing its magnitude until v reaches zero. It can then speed up in the opposite direction.'))
lab('linear-position','distance','Displacement remembers only the endpoints',
    'Move to a turning point and return partway. Watch the path length grow while the endpoint displacement can shrink.',
    'Motion along one line: start at 0 m, travel to A ≥ 0, then travel back by B ≥ 0. This lab shows geometry rather than a time law.',
    [step('Locate the endpoint',r'x_f=A-B','Subtract the return distance because that leg points in the negative direction.'),step('Compare endpoints',r'\Delta x=x_f-x_i=A-B','Displacement is signed and ignores the route taken.'),step('Add every part of the path',r'd=A+B\ge|\Delta x|','Distance is nonnegative. Equality holds only when the path has no reversal over a nonzero distance.')],
    prediction('Returning exactly to the start gives…',['zero displacement, nonzero distance','zero displacement and zero distance'],0,'For a nonzero outward journey A and an equal return B, displacement is A − B = 0 but distance is 2A.'))
lab('vectors-components','components','Resolve the arrow, keep its identity',
    'Rotate a vector through all four quadrants. Its component arrows change sign while its magnitude stays fixed.',
    'Angle θ is measured counterclockwise from +x. All arrow lengths represent metres; screen geometry is drawn to scale.',
    [step('Project onto the x axis',r'A_x=A\cos\theta','The adjacent side is the horizontal projection. Cosine supplies the sign in each quadrant.'),step('Project onto the y axis',r'A_y=A\sin\theta','The vertical projection uses sine for this angle convention. An angle measured from y would exchange the roles.'),step('Reconstruct the original vector',r'A=\sqrt{A_x^2+A_y^2}','Squaring removes component signs, so the reconstructed magnitude is nonnegative and independent of the direction.')],
    prediction('In the second quadrant, the component signs are…',['x negative, y positive','x positive, y negative'],0,'The vector points left and up: the x projection is negative and the y projection is positive.'))
lab('vectors-dot','projection','The dot product measures useful alignment',
    'Rotate a force relative to a horizontal displacement. The projection onto the displacement shows why work can be positive, zero, or negative.',
    'Constant force F = 10 N; displacement s = 3 m along +x. The varying angle is between force and displacement, not between force and the vertical.',
    [step('Select the parallel component',r'F_\parallel=F\cos\theta','Only the force component along the displacement contributes to work.'),step('Multiply by the displacement',r'W=\vec F\cdot\vec s=Fs\cos\theta','F is in N, s in m, and W in J. Perpendicular force has zero work for this displacement.'),step('Read the sign geometrically',r'\theta<90^\circ:\ W>0;\quad\theta>90^\circ:\ W<0','A component along motion supplies energy; one opposing motion removes energy. A negative result is not a negative force magnitude.')],
    prediction('At 90°, the force does…',['zero work on this displacement','maximum positive work'],0,'The parallel component vanishes because cos 90° = 0, even though the force itself is nonzero.'))
lab('plane-projectiles','projectile','Gravity bends the path, not the horizontal speed',
    'Play a projectile and watch independent horizontal and vertical velocity arrows. Compare 30° and 60° launches.',
    'Point projectile; no air drag; g = 10 m/s²; launch and landing at the same height. The drawing scale is fixed across launch angles.',
    [step('Resolve the launch velocity',r'u_x=u\cos\theta,\qquad u_y=u\sin\theta','The components share the same time. Their units are m/s.'),step('Evolve each direction',r'x=u_x t,\qquad y=u_y t-\frac12gt^2','No horizontal force means constant uₓ. Gravity changes vᵧ = uᵧ − gt while aᵧ remains −g.'),step('Return to launch height',r'T=\frac{2u\sin\theta}{g},\qquad R=\frac{u^2\sin2\theta}{g}','The nonzero root of y = 0 gives flight time; substitute it into x to obtain the range. These results need equal launch and landing heights.')],
    prediction('At the top of an oblique projectile path…',['vertical velocity is zero; acceleration is downward','both velocity and acceleration are zero'],0,'Only vᵧ vanishes. The horizontal component persists and gravity still acts downward.'))
lab('plane-relative','river','Aim upstream or arrive downstream',
    'Choose a swimming angle and add the water velocity to the swimmer’s velocity. Watch the actual route across a river.',
    'River width = 40 m; uniform stream along +x. Swim speed is relative to water; θ is measured upstream from straight across. No current variation or acceleration.',
    [step('Write relative velocity',r'\vec v_{\rm ground}=\vec v_{\rm swim/water}+\vec v_{\rm water/ground}','The river carries the swimmer while the swimmer moves through the water.'),step('Resolve the ground components',r'v_x=v_r-v_s\sin\theta,\qquad v_y=v_s\cos\theta','vᵣ is the stream speed and vₛ is swim speed, both in m/s. Positive θ aims upstream.'),step('Find crossing time and drift',r't=\frac{w}{v_y},\qquad d=v_xt','w is river width (m). Zero drift requires sin θ = vᵣ/vₛ, possible only when swim speed is at least the stream speed; equality cannot give a finite crossing time.')],
    prediction('The shortest crossing time is obtained by aiming…',['straight across relative to water','at the zero-drift angle'],0,'Straight across maximises the cross-river component. Aiming upstream removes drift at the cost of a smaller cross-river speed.'))
lab('plane-circular','circle','A changing direction is an acceleration',
    'Follow an object around a circle. Its velocity is tangent; the acceleration arrow always points toward the centre.',
    'Uniform circular motion; radius r in m and speed v in m/s. Vector lengths are scaled separately and labelled, so acceleration length is not a speed.',
    [step('Velocity follows the tangent',r'\omega=\frac vr','Angular speed ω (rad/s) connects arc speed to radius.'),step('Compare nearby velocities',r'\frac{|\Delta\vec v|}{\Delta t}\to\frac{v^2}{r}','The velocity changes because its direction changes, even though the speed stays constant.'),step('Find the required inward force',r'a_c=\frac{v^2}{r},\qquad F_{\rm net,in}=m\frac{v^2}{r}','Centripetal names the inward resultant, not a new extra force. Identify which real force supplies it in the problem.')],
    prediction('Doubling speed at fixed radius makes the required acceleration…',['four times as large','twice as large'],0,'Acceleration depends on v², so doubling v produces a factor of four.'))
lab('laws-connected','atwood','Two masses, one string, two force equations',
    'Change the two masses on an ideal pulley. Separate their free-body diagrams before combining the equations.',
    'Massless inextensible string; massless frictionless fixed pulley; g = 10 m/s². Equal tension on both sides and equal acceleration magnitudes. Travel is shown over a limited interval.',
    [step('Choose the positive direction for each mass',r'm_2g-T=m_2a','For the right mass, downward is positive. A negative a means this mass actually accelerates upward.'),step('Use the string constraint',r'T-m_1g=m_1a','For the left mass, upward is positive. The shared string imposes the same signed coordinate acceleration in these chosen directions.'),step('Eliminate the internal tension',r'a=\frac{m_2-m_1}{m_1+m_2}g,\qquad T=\frac{2m_1m_2g}{m_1+m_2}','Add the equations to cancel T. Substitute the acceleration into either equation to recover the tension.')],
    prediction('For two equal masses released from rest…',['acceleration is zero and tension equals either weight','tension is zero'],0,'Each mass is in equilibrium: T = mg. Opposing weights cancel for the system, not on each individual mass.'))
lab('laws-lift','lift','A scale reads support force',
    'Choose an upward or downward acceleration and compare weight with the force from the floor. Free fall makes the scale read zero.',
    'Person mass = 60 kg; g = 10 m/s²; upward acceleration is positive. The scale displays normal force in N. Contact is maintained for a ≥ −g.',
    [step('Identify forces on the person',r'F_y=N-mg','N is the upward normal force; mg is downward gravitational force. Do not add velocity as a force.'),step('Apply Newton’s second law',r'N-mg=ma','a is the lift’s acceleration, not its direction of motion.'),step('Read the scale',r'N=m(g+a)','Upward acceleration raises the reading; downward acceleration lowers it. At a = −g the support force vanishes while gravity remains.')],
    prediction('A lift moving downward but slowing down gives a reading…',['greater than mg','less than mg'],0,'Slowing while moving down means acceleration is upward. Thus N = m(g+a) exceeds mg.'))
lab('friction-static','friction','Static friction adjusts before sliding begins',
    'Increase the horizontal pull. Friction matches it until the maximum static value is exceeded, then switches to kinetic friction.',
    'Block mass = 2 kg; horizontal surface; g = 10 m/s²; μₛ = 0.6 and μₖ = 0.4. At the exact limiting force the lab keeps the block at impending motion.',
    [step('Find the normal force',r'N=mg=20\ \mathrm{N}','There is no vertical acceleration or vertical component of the pull.'),step('Test the static limit',r'0\le f_s\le\mu_sN=12\ \mathrm{N}','While at rest, actual friction equals the applied horizontal force. μₛN is a maximum, not an automatic value.'),step('Use the sliding law after motion starts',r'f_k=\mu_kN=8\ \mathrm{N},\qquad a=\frac{F-f_k}{m}','Kinetic friction opposes sliding. The sudden reduction from limiting static friction explains why starting motion can need more effort than maintaining it.')],
    prediction('A 5 N pull on this initially resting block produces friction…',['5 N','12 N'],0,'Static friction supplies just enough to balance the pull. The 12 N value is its available maximum.'))
lab('friction-inclines','incline','The angle decides whether the block can stay',
    'Tilt the plane and compare the downhill component of weight with the available static friction. Watch the threshold emerge.',
    'Mass = 2 kg; g = 10 m/s²; μₛ = 0.5, μₖ = 0.3. The block starts at rest. Downhill is positive; the illustration magnifies forces independently of geometry.',
    [step('Resolve the weight',r'F_{\parallel}=mg\sin\theta,\qquad N=mg\cos\theta','The normal is perpendicular to the incline. It is less than mg at a nonzero angle.'),step('Test whether rest is possible',r'mg\sin\theta\le\mu_smg\cos\theta','Static friction points uphill and can match the downhill force until its maximum is reached.'),step('Find the angle of repose',r'\tan\theta_r=\mu_s','Mass and gravity cancel. Above this threshold, a = g(sin θ − μₖ cos θ) for downhill sliding.')],
    prediction('Increasing mass alone changes the angle of repose…',['not at all in this model','to a larger angle'],0,'Both the downhill weight component and the friction limit are proportional to mass, so mass cancels from the rest condition.'))
lab('work-spring','spring-energy','Follow energy from a spring into motion',
    'Play a frictionless spring oscillator and watch potential energy turn into kinetic energy. Their sum stays fixed.',
    'Horizontal ideal spring; k = 20 N/m, mass = 1 kg, amplitude = 0.5 m. No damping. x is displacement from equilibrium.',
    [step('A changing restoring force',r'F=-kx','The force points toward equilibrium. k is stiffness (N/m), x displacement (m).'),step('Store energy by stretching',r'U(x)=\int_0^x kx^{\prime}dx^{\prime}=\frac12kx^2','The area under force magnitude versus stretch is a triangle, giving the factor one-half.'),step('Conserve the total energy',r'E=\frac12kA^2,\qquad K=E-U=\frac12k(A^2-x^2)','A is amplitude. K is greatest at equilibrium; U is greatest at either turning point.')],
    prediction('At equilibrium, the spring oscillator has…',['maximum kinetic energy','zero total energy'],0,'At x = 0, U = 0 but K = E. The restoring force is zero there; the oscillator keeps moving because its velocity is maximum.'))
lab('work-collisions','collision','Momentum survives; kinetic energy may not',
    'Change the coefficient of restitution, then play two carts before and after impact. Compare momentum and kinetic energy.',
    'One-dimensional isolated collision; cart masses 1 kg and 2 kg; incoming speeds 6 m/s and 0; e between 0 and 1; impact is instantaneous.',
    [step('Conserve total momentum',r'm_1u_1+m_2u_2=m_1v_1+m_2v_2','No external impulse acts during impact. Momentum conservation applies to elastic and inelastic collisions.'),step('Specify the collision behaviour',r'v_2-v_1=e(u_1-u_2)','e is restitution: separation speed divided by approach speed, for these chosen directions.'),step('Account for the energy change',r'\Delta K=\frac12\frac{m_1m_2}{m_1+m_2}(1-e^2)(u_1-u_2)^2','ΔK here is kinetic energy lost, in J. For e = 0 both carts leave with a common velocity; for e = 1 no kinetic energy is lost.')],
    prediction('In a perfectly inelastic isolated collision…',['momentum is conserved but kinetic energy decreases','momentum and kinetic energy both vanish'],0,'The carts stick with the centre-of-mass velocity. Some kinetic energy becomes internal energy; total momentum remains unchanged.'))
lab('work-vertical-loop','loop','The top of the loop sets the minimum launch',
    'Raise the bottom launch speed. Follow the speed and string tension, and see when a taut circular trajectory is possible.',
    'Point mass = 1 kg on a massless string of length R = 1 m; g = 10 m/s²; no drag. If the circular solution needs negative tension, the lab stops at the first loss of tension; it does not pretend the later path stays circular.',
    [step('Use energy to find speed at height',r'v^2=v_0^2-2gR(1-\cos\theta)','θ is angle measured from the bottom. Height gained is R(1 − cos θ).'),step('Write the inward force equation',r'T=m\left(\frac{v^2}{R}+g\cos\theta\right)','At the bottom, T − mg = mv²/R. At the top, T + mg = mv²/R.'),step('Impose the taut-string condition',r'v_{\rm top}^2\ge gR\quad\Rightarrow\quad v_0^2\ge5gR','A string can pull but cannot push. The limiting full-loop case has zero tension at the top.')],
    prediction('The minimum bottom speed for a complete taut loop is…',['√(5gR)','√(4gR)'],0,'√(4gR) only supplies the height energy to reach the top at zero speed. Additional speed is required to maintain inward acceleration with nonnegative tension.'))
lab('rotation-centre','centre-mass','The balancing point follows the mass',
    'Move two masses and adjust their ratio. The centre of mass shifts toward the heavier mass, not necessarily toward the geometric midpoint.',
    'Two point masses on a horizontal massless rod; positions in m from a fixed origin. The displayed support at x_CM would balance the rod in uniform gravity.',
    [step('Weight each position by its mass',r'\sum m_ix_i=m_1x_1+m_2x_2','A larger mass contributes more to the total position moment.'),step('Divide by the total mass',r'x_{CM}=\frac{m_1x_1+m_2x_2}{m_1+m_2}','Positions can be positive or negative. x_CM has units m.'),step('Check the balance',r'm_1(x_{CM}-x_1)=m_2(x_2-x_{CM})','For x₁ < x₂, the torques of the weights about the support balance. This verifies the weighted-average result.')],
    prediction('If the right-hand mass grows while positions stay fixed, x_CM moves…',['toward the right mass','toward the left mass'],0,'The heavier mass receives more weight in the average. The centre remains between the two positions for positive masses.'))
lab('rotation-rolling','rolling','Same height, different shares of energy',
    'Race a hoop, a solid disc, and a solid sphere down the same incline. Track translation and rotation separately.',
    'Uniform bodies; same mass = 1 kg, radius = 0.2 m; g = 10 m/s²; incline angle = 20°. Sufficient static friction prevents slipping; no rolling resistance.',
    [step('Apply the no-slip constraint',r'v=\omega R','Translation and rotation are linked. This constraint needs enough static friction.'),step('Share the available energy',r'mgh=\frac12mv^2+\frac12I\omega^2','Define β = I/(mR²): 1 for a hoop, 1/2 for a disc, 2/5 for a solid sphere.'),step('Solve for speed and acceleration',r'v^2=\frac{2gh}{1+\beta},\qquad a=\frac{g\sin\theta}{1+\beta}','A smaller β leaves a larger fraction for translation, so the sphere accelerates fastest. Static friction does no net work for ideal rolling on a fixed plane.')],
    prediction('Which reaches the bottom first in this ideal race?',['solid sphere','hoop'],0,'The solid sphere has the smallest I/(mR²), hence the greatest downhill acceleration. All share the same total energy at a given height.'))
lab('gravitation-orbits','orbit','An orbit is continuous free fall',
    'Change the orbit radius and watch the speed and period respond. Gravity turns the velocity rather than requiring an engine to sustain the orbit.',
    'Circular orbit around a spherical Earth; R = 6.4 × 10⁶ m, surface g₀ = 10 m/s²; satellite mass negligible; no atmosphere. Animation compresses the time scale.',
    [step('Match gravity to the inward requirement',r'\frac{GMm}{r^2}=\frac{mv^2}{r}','r is distance from the centre, not altitude. Satellite mass cancels.'),step('Find the circular speed',r'v=\sqrt{\frac{GM}{r}}','Higher circular orbits have lower speed. GM = g₀R² is used here.'),step('Divide circumference by speed',r'T=\frac{2\pi r}{v}=2\pi\sqrt{\frac{r^3}{GM}}','The longer path and lower speed both increase the period. A weightless astronaut still experiences gravitational acceleration.')],
    prediction('Doubling orbital radius multiplies the circular period by…',['2√2','2'],0,'T is proportional to r^(3/2), so the factor is 2^(3/2), not simply the circumference factor of two.'))
lab('gravitation-spherical','gravity-profile','Inside and outside are different laws',
    'Move a test point from the centre through the surface and into space. Compare the enclosed mass with the inverse-square law.',
    'Uniform-density, nonrotating sphere. Radius coordinate r/R; gravity normalised by surface value g₀. This is not a realistic Earth density model.',
    [step('Use only the enclosed mass inside',r'M(r)=M\left(\frac rR\right)^3','Outer spherical shells give zero net field at an interior point. Uniform density makes mass proportional to r³.'),step('Find the interior field',r'g(r)=\frac{GM(r)}{r^2}=g_0\frac rR','The magnitude grows linearly from zero at the centre to g₀ at the surface.'),step('Use the full mass outside',r'g(r)=g_0\left(\frac Rr\right)^2\quad(r\ge R)','Beyond the sphere, its field equals that of a point mass at the centre. Both expressions meet continuously at the surface.')],
    prediction('At the centre of this uniform sphere, the gravitational field is…',['zero','infinite'],0,'Symmetry makes contributions cancel. The interior law uses enclosed mass, so applying GM/r² with the full M at r = 0 is invalid.'))
lab('oscillations-phase','shm','A rotating projection reveals SHM',
    'Follow uniform circular motion and its horizontal projection. Link phase with displacement, velocity, and acceleration.',
    'Ideal SHM: A = 0.2 m; frequency f can change; x = A cos(2πft). The circle is a mathematical reference, not the actual path of a spring mass.',
    [step('Project the rotating radius',r'x=A\cos\phi,\qquad\phi=\omega t','ω = 2πf is angular frequency (rad/s). Equal phase intervals do not mean equal displacement intervals.'),step('Differentiate once',r'v=-A\omega\sin\phi','Velocity is zero at the extremes and greatest in magnitude at equilibrium.'),step('Differentiate again',r'a=-\omega^2x','Acceleration is opposite to displacement and proportional to it: the defining SHM condition.')],
    prediction('At the positive extreme x = A, the oscillator has…',['zero velocity and maximum negative acceleration','maximum positive velocity and zero acceleration'],0,'The mass is instantaneously at rest, but the restoring force and acceleration point strongly back toward equilibrium.'))
lab('oscillations-pendulum','pendulum','A pendulum tests the small-angle approximation',
    'Compare a small swing with a larger swing and inspect the restoring force. Change length to see the ideal small-angle period.',
    'g = 10 m/s²; point bob; massless string; no damping. Animation solves θ̈ = −(g/L) sin θ. The displayed 2π√(L/g) is a small-angle prediction, not the exact finite-amplitude period.',
    [step('Resolve gravity tangentially',r'F_t=-mg\sin\theta','θ is measured from the downward vertical in radians. The radial component is handled by the string tension.'),step('Use arc displacement',r's=L\theta,\qquad\ddot\theta=-\frac gL\sin\theta','The exact equation is nonlinear because of sin θ.'),step('Approximate a small swing',r'\sin\theta\approx\theta\quad\Rightarrow\quad T_0=2\pi\sqrt{\frac Lg}','For small amplitudes the motion is SHM. Large swings have a longer period; the leading fractional correction is approximately θ₀²/16 with θ₀ in radians.')],
    prediction('Doubling pendulum length makes the small-angle period…',['√2 times as long','twice as long'],0,'The period scales as the square root of length. The bob mass cancels from the equation.'))
lab('waves-travelling','travelling-wave','The wave travels; the particles stay local',
    'Play a transverse wave and follow a highlighted particle. The pattern moves right while the marked particle only moves up and down.',
    'Ideal sinusoidal transverse wave with amplitude A = 0.15 m. Speed v and frequency f set λ = v/f. The medium is represented by discrete sample particles.',
    [step('Describe one particle',r'y(x,t)=A\sin(kx-\omega t)','x labels a particle’s equilibrium position. A is displacement amplitude, k = 2π/λ, ω = 2πf.'),step('Follow a fixed phase',r'kx-\omega t=\mathrm{constant}','To keep the same phase as time increases, x must increase. The minus sign denotes rightward propagation.'),step('Connect pattern speed to wavelength',r'v=\frac\omega k=f\lambda','Particle velocity is ∂y/∂t and is vertical here. It is different from the horizontal propagation speed.')],
    prediction('The highlighted medium particle…',['oscillates locally while the pattern travels','travels to the right with each crest'],0,'A wave transports energy through the medium; in this ideal transverse model each particle has a fixed horizontal equilibrium position.'))
lab('waves-modes','standing-wave','Nodes do not move when the string vibrates',
    'Choose a harmonic of a string fixed at both ends. Watch stationary nodes divide the string into loops.',
    'String length L = 2 m; wave speed v = 4 m/s; fixed ends; harmonic n is a positive integer. Damping and driving are omitted.',
    [step('Fit whole half-wavelengths',r'L=n\frac\lambda2','Each loop contains one half-wavelength. The two fixed endpoints must be nodes.'),step('Find the allowed frequency',r'\lambda_n=\frac{2L}{n},\qquad f_n=\frac{nv}{2L}','Frequency changes discretely with harmonic number; n is not a continuous slider value.'),step('Combine counter-propagating waves',r'y=2A\sin\left(\frac{n\pi x}{L}\right)\cos(2\pi f_nt)','The spatial factor fixes nodes where it vanishes. All particles between adjacent nodes oscillate in phase; the neighbouring loop has opposite phase.')],
    prediction('In the third harmonic, the number of internal nodes is…',['two','three'],0,'There are n + 1 nodes including both endpoints. The third harmonic therefore has two internal nodes and three loops.'))
lab('waves-beats','beats','Two nearby tones make a slow envelope',
    'Vary the small frequency difference. Compare the rapid oscillation with the slowly changing combined amplitude.',
    'Two equal-amplitude waves at the same point with frequencies f₁ = 20 Hz and f₂ close to it. These low illustrative frequencies make the oscillations visible; no audio is generated.',
    [step('Add both disturbances',r'y=A\cos(2\pi f_1t)+A\cos(2\pi f_2t)','Superposition adds displacements, not intensities.'),step('Separate carrier and envelope',r'y=2A\cos[\pi(f_2-f_1)t]\cos[\pi(f_1+f_2)t]','The average frequency gives rapid oscillation; the difference controls the slow modulation.'),step('Count loudness maxima',r'f_{\rm beat}=|f_2-f_1|','Intensity follows amplitude squared, so both positive and negative envelope peaks give loudness maxima. This removes the apparent factor-of-two ambiguity.')],
    prediction('Two equal-amplitude tones with exactly equal frequency and phase produce…',['constant doubled amplitude, no beats','beats at twice the frequency'],0,'Their phase difference never changes. The amplitude stays 2A, so there is no slow modulation.'))
lab('thermal-properties-expansion','expansion','The hole expands too',
    'Heat a uniform plate with a circular hole. Compare the original outline with the expanded plate and its expanded hole.',
    'Uniform isotropic plate; α = 2 × 10⁻⁵ K⁻¹; temperature change ΔT in K; no constraint. Drawing exaggerates strain by a stated factor; readouts use the actual strain.',
    [step('Scale every linear dimension',r'L=L_0(1+\alpha\Delta T)','α is linear expansion coefficient (K⁻¹). A free hole follows the same geometrical scaling as the surrounding material.'),step('Square the scale factor for area',r'A=A_0(1+\alpha\Delta T)^2','Both outer area and hole area grow. The hole behaves as if filled with the same freely expanding material.'),step('Keep only first-order terms when appropriate',r'\frac{\Delta A}{A_0}\approx2\alpha\Delta T','For small αΔT, the quadratic correction can be neglected. A constrained plate instead develops stress and is a different model.')],
    prediction('Heating a freely expanding uniform plate makes its hole…',['larger','smaller'],0,'Every distance between material points increases by the same factor. The material does not simply grow inward into the empty hole.'))
lab('thermal-properties-latent','phase-change','Heat can change the state without changing temperature',
    'Add energy to ice initially at −10°C. Track warming, melting, and warming the resulting water.',
    'Mass = 0.1 kg; c_ice = 2100 J/(kg K); L_f = 334000 J/kg; c_water = 4200 J/(kg K); pressure fixed; no heat loss; boiling is outside the slider range.',
    [step('Warm the solid to its melting point',r'Q_1=mc_{\rm ice}(0-(-10))=2100\ \mathrm{J}','Before melting, added energy increases temperature.'),step('Change phase at 0°C',r'Q_{\rm melt}=mL_f=33400\ \mathrm{J}','The next energy changes the melted fraction while the equilibrium temperature remains 0°C.'),step('Warm the liquid after all ice melts',r'T=\frac{Q-Q_1-mL_f}{mc_{\rm water}}','This expression applies only after Q exceeds Q₁ + mL_f. Earlier stages need their own energy balance.')],
    prediction('During equilibrium melting, extra heat mainly changes…',['the melted fraction','the temperature above 0°C'],0,'Ice and water coexist at the melting temperature under the stated pressure. Heat supplies latent energy until the ice is gone.'))
lab('thermal-properties-cooling','cooling','Equal time intervals remove a fraction, not a fixed temperature',
    'Compare cooling curves for different rate constants. Watch the temperature difference shrink exponentially toward the surroundings.',
    'Uniform body; constant ambient T_a = 20°C; initial temperature 80°C; Newton cooling coefficient k in min⁻¹; approximation assumes the heat-transfer conditions stay constant.',
    [step('Compare with the surroundings',r'\frac{dT}{dt}=-k(T-T_a)','Cooling rate depends on excess temperature, not temperature measured from 0°C.'),step('Separate and integrate',r'\ln\frac{T-T_a}{T_0-T_a}=-kt','T₀ is the initial temperature. The logarithm contains a dimensionless ratio.'),step('Recover the temperature',r'T(t)=T_a+(T_0-T_a)e^{-kt}','Equal times multiply the excess temperature by the same factor. The ideal curve approaches ambient asymptotically.')],
    prediction('As the body approaches ambient temperature, its cooling rate…',['decreases in magnitude','stays constant'],0,'The driving temperature difference gets smaller. A straight-line temperature drop is only a short-interval approximation.'))
lab('kinetic-theory-pressure','gas','Pressure emerges from many wall impacts',
    'Watch representative molecules reflect from the walls. Change absolute temperature and relate their motion to the gas pressure.',
    'Ideal gas in a 1 L container; n = 0.01 mol; molar mass M = 0.028 kg/mol. Molecules shown are 2D representative tracers; pressure and rms speed readouts use the 3D ideal-gas laws, not a count of drawn collisions.',
    [step('One reflection changes momentum',r'\Delta p_x=2mv_x','For an elastic wall impact, the normal velocity component reverses. The impulse on the wall is opposite to that on the molecule.'),step('Average over isotropic motion',r'P=\frac13\rho\langle v^2\rangle','The factor 1/3 comes from equal mean squared components in three dimensions.'),step('Connect kinetic energy with temperature',r'P=\frac{nRT}{V},\qquad v_{\rm rms}=\sqrt{\frac{3RT}{M}}','T must be in kelvin; M must be in kg/mol. The visual is illustrative, while the displayed pressure is quantitatively calculated.')],
    prediction('At fixed volume and amount, doubling absolute temperature makes pressure…',['double','increase by √2'],0,'Pressure is proportional to T. The √2 factor applies to rms speed, not to pressure.'))
lab('kinetic-theory-equipartition','degrees','Degrees of freedom count energy stores',
    'Switch between a monatomic gas, a diatomic gas with active rotation, and a diatomic model with one active vibration. Compare heat capacities.',
    'Ideal gas; classical equipartition for the explicitly active modes. A vibrational mode adds both kinetic and potential energy terms. Real activation depends on temperature and molecule.',
    [step('Assign energy to quadratic terms',r'\langle E\rangle=\frac f2 k_BT','f counts active quadratic terms. Translation contributes 3; diatomic rotation contributes 2; one vibrational mode contributes 2.'),step('Differentiate the molar internal energy',r'U=\frac f2 nRT,\qquad C_V=\frac f2R','Cᵥ is molar constant-volume heat capacity, in J/(mol K), when f stays fixed over the temperature range.'),step('Relate constant-pressure heating',r'C_P=C_V+R,\qquad\gamma=1+\frac2f','The extra R accounts for expansion work at constant pressure. Larger f lowers γ.')],
    prediction('Activating another energy mode generally makes γ…',['smaller','larger'],0,'Adding degrees of freedom raises Cᵥ. Because γ = 1 + R/Cᵥ, the ratio decreases.'))
lab('thermodynamics-work','pv','Same endpoints do not determine the work',
    'Compare isothermal, isobaric, and reversible adiabatic expansion from the same initial state. Shade the actual area under each path.',
    'One mol ideal gas; T₁ = 300 K; V₁ = 0.01 m³; γ = 1.4; R = 8.314 J/(mol K). Slow reversible paths, with no other work. These paths share the initial state and final volume, but generally not the final temperature.',
    [step('Work depends on the pressure along the path',r'W=\int_{V_1}^{V_2}P(V)\,dV','Expansion has positive work by the gas. The area is measured in Pa m³ = J.'),step('Choose a physical path law',r'P=P_1;\quad P=\frac{nRT_1}{V};\quad PV^\gamma=\mathrm{constant}','These correspond to isobaric, isothermal, and reversible adiabatic paths. Do not exchange their formulas.'),step('Close the energy account',r'Q=\Delta U+W,\qquad\Delta U=nC_V(T_2-T_1)','For isothermal ideal-gas expansion ΔU = 0; for adiabatic expansion Q = 0 and the gas cools.')],
    prediction('For the same initial state and final expanded volume, which path gives more work?',['isobaric than isothermal','adiabatic than isothermal'],0,'At every intermediate volume during expansion, the isobaric pressure lies above the isothermal curve, which lies above the adiabat. Compare their areas.'))
lab('thermodynamics-second-law','engine','A heat engine must reject some heat',
    'Change the reservoir temperatures. Track heat absorbed, heat rejected, and the maximum possible work for a reversible engine.',
    'Carnot engine between ideal reservoirs; Q_h = 1000 J per cycle; temperatures in K with 0 < T_c < T_h. A real engine has efficiency no greater than this bound.',
    [step('Apply a full-cycle energy balance',r'\Delta U_{\rm cycle}=0,\qquad W=Q_h-Q_c','The working substance returns to its initial state, but heat and work transfer energy around the cycle.'),step('Use reversibility for the limiting engine',r'\frac{Q_c}{Q_h}=\frac{T_c}{T_h}','The two reservoir temperatures are absolute temperatures, not Celsius values.'),step('Find the efficiency limit',r'\eta_C=\frac W{Q_h}=1-\frac{T_c}{T_h}','Efficiency can improve by raising Tₕ or lowering T𝚌. It cannot reach 100% with a positive cold-reservoir temperature.')],
    prediction('A Carnot engine between 600 K and 300 K has efficiency…',['50%','100%'],0,'η = 1 − 300/600 = 0.5. The remaining 50% of input heat must be rejected to the cold reservoir.'))
lab('thermodynamics-adiabatic','mixing','Connected rigid vessels: conserve energy before using pressure',
    'Open the connection between two rigid insulated vessels of the same ideal gas. Compare the initial temperatures with the equilibrium state.',
    'Same ideal gas and the same constant molar Cᵥ in both vessels; n₁ = n₂ = 1 mol; V₁ = V₂ = 0.01 m³. Whole combined system is rigid and insulated. Animation is illustrative, not a fluid-flow simulation.',
    [step('Choose both vessels as the system',r'Q_{\rm ext}=0,\qquad W_{\rm ext}=0\quad\Rightarrow\quad\Delta U_{\rm total}=0','Gas may do internal work on other gas, but it does not cross the rigid outer boundary. Internal transfers cancel in the total balance.'),step('Use the ideal-gas internal energy',r'T_f=\frac{n_1C_VT_1+n_2C_VT_2}{(n_1+n_2)C_V}','For the same gas, Cᵥ cancels; equal amounts give the arithmetic mean. Different gases require heat-capacity weighting.'),step('Use the combined final volume',r'P_f=\frac{(n_1+n_2)RT_f}{V_1+V_2}','This irreversible equilibration does not obey PV^γ = constant as a path law. Adiabatic means no external heat, not necessarily reversible.')],
    prediction('Opening the valve between these vessels requires applying…',['total energy conservation','PV^γ = constant to each vessel'],0,'The combined system conserves energy. Individual vessels exchange matter, and the valve-opening process is irreversible, so the reversible adiabatic path law is inappropriate.'))

# The visible teaching path is problem-first. Derivations remain optional.
PROBLEM_GUIDES = {
 'tangent':('A question gives x(t) and asks for velocity at an instant.',['Differentiate x(t) once.','Substitute the requested time, keeping seconds throughout.','Read the sign as direction; speed is the magnitude.']),
 'integral':('A force changes with position and you need its work.',['Read the force and position axes with their units.','Find the signed area over the stated displacement.','Use triangles/rectangles if the graph is simple; otherwise integrate.']),
 'vernier':('You are given a caliper diagram or scale readings.',['Read the main mark just before the vernier zero.','Add coincident division × least count.','Subtract the zero error and report the correct precision.']),
 'uncertainty':('A quantity is calculated from measured lengths or masses.',['Write its dependence as a product of powers.','Multiply each percentage uncertainty by the absolute power.','Add those contributions for the small-error worst-case bound.']),
 'kinematics':('Motion has constant acceleration and the question asks for x, v or t.',['Choose a positive direction and assign signs to u and a.','Pick the constant-acceleration equation containing the known quantities.','Check whether the object reverses direction before interpreting distance.']),
 'distance':('A journey has more than one direction.',['Add the lengths of all legs for distance.','Subtract initial position from final position for displacement.','Use displacement for average velocity; distance for average speed.']),
 'components':('A force or velocity acts at an angle.',['Draw the angle from the stated reference axis.','Resolve along your chosen axes with sine and cosine.','Assign component signs before adding other vectors.']),
 'projection':('A constant force acts while an object moves in a stated direction.',['Find the angle between force and displacement.','Use W = Fs cos θ, with F in N and s in m.','Check the sign: helping motion gives positive work.']),
 'projectile':('A projectile moves under gravity without air resistance.',['Resolve the initial velocity into x and y.','Find time from the vertical motion.','Use the same time in horizontal motion; use the range shortcut only for equal heights.']),
 'river':('A swimmer, boat or aircraft moves through a moving medium.',['Add the medium velocity to velocity relative to the medium.','Use only the across-river component to find crossing time.','Multiply along-river ground speed by that time for drift.']),
 'circle':('An object follows a circular path.',['Identify the radius and speed at the chosen point.','Resolve real forces toward the centre.','Set their inward resultant equal to mv²/r.']),
 'atwood':('Connected masses move over an ideal pulley.',['Draw forces separately for each mass.','Use the string constraint to relate accelerations.','Add equations to get a, then substitute back for T.']),
 'lift':('A question asks what a scale reads in an accelerating lift.',['Choose upward positive and determine the acceleration sign.','Use N = m(g + a).','If only motion direction is given, look for whether it is speeding up or slowing down.']),
 'friction':('A resting block is pulled along a rough surface.',['Calculate the maximum available static friction μₛN.','If the pull is below that limit, actual friction matches the pull.','After sliding begins, use μₖN and calculate the net force.']),
 'incline':('A body rests or slides on a rough incline.',['Resolve mg into mg sin θ along the plane and mg cos θ normal to it.','Test whether available static friction can balance the downhill force.','For sliding, subtract kinetic friction from the downhill force.']),
 'spring-energy':('A spring changes length and the question asks about speed or energy.',['Measure spring extension from its natural length.','Write spring energy as ½kx².','Compare total energies at the two positions; include other forces if they do work.']),
 'collision':('Two bodies collide in one dimension.',['Conserve momentum for the isolated pair.','Use the given restitution or sticking condition as the second equation.','Check kinetic energy separately; it is conserved only for an elastic collision.']),
 'loop':('A string-bound mass must complete a vertical circle.',['Use energy to relate bottom and top speeds.','At the top set T + mg = mv²/R.','For the minimum full-loop speed set the top tension to zero.']),
 'centre-mass':('Masses are located at different positions.',['Choose one origin for all positions.','Multiply each position by its mass and add.','Divide by total mass; the result should lie between positive-mass positions.']),
 'rolling':('A body rolls without slipping down an incline.',['Identify β = I/(mR²) for the shape and axis.','Use v = ωR to combine translational and rotational energy.','Use v² = 2gh/(1 + β), or a = g sin θ/(1 + β) when needed.']),
 'orbit':('A satellite is in a circular orbit.',['Convert altitude h to centre distance r = R + h.','Use v = √(GM/r) for speed.','Use T = 2πr/v for period; compare radii with T ∝ r³ᐟ².']),
 'gravity-profile':('Gravity is asked for above the surface or inside a uniform sphere.',['Decide whether the point is inside or outside.','Inside a uniform sphere use g/g₀ = r/R; outside use (R/r)².','Convert depth to r = R − d or altitude to r = R + h.']),
 'shm':('A question gives displacement, phase or energy of ideal SHM.',['Identify A and ω, converting frequency with ω = 2πf.','Use the phase to find x; use a = −ω²x for acceleration.','For speed at a position, use v² = ω²(A² − x²).']),
 'pendulum':('A simple pendulum has a small swing.',['Find the effective gravity along the equilibrium direction.','Use T = 2π√(L/g_eff).','Use a period ratio when only length or gravity changes; mass cancels.']),
 'travelling-wave':('A travelling-wave equation or speed–frequency relation is given.',['Read amplitude, k and ω from the equation with their units.','Use λ = 2π/k, f = ω/(2π), and v = ω/k.','Keep particle motion separate from propagation direction.']),
 'standing-wave':('A string fixed at both ends vibrates in a harmonic.',['Count the loops to identify harmonic n.','Use λ = 2L/n and f = nv/(2L).','Count internal nodes as n − 1; include endpoints only if asked.']),
 'beats':('Two nearby tones produce beats.',['Use beat frequency as the absolute difference of tone frequencies.','If a fork is loaded, its frequency falls.','Use whether beats increase or decrease to choose the correct unknown frequency.']),
 'expansion':('A freely expanding rod, plate or hole is heated.',['Choose linear, area or volume expansion for the requested dimension.','Use ΔL = αL₀ΔT, or the small-strain area factor 2α.','Expand a hole by the same scaling; constrained expansion is a different problem.']),
 'phase-change':('Ice or water receives heat or is mixed with something warmer.',['First pay the heat needed to reach the phase-change temperature.','Use mL for melting or freezing while temperature stays fixed.','Only after the phase change is complete use mcΔT for the next temperature rise.']),
 'cooling':('A body cools toward a constant ambient temperature.',['Subtract the ambient temperature from each reading.','Compare those excess temperatures over the time interval.','Use exponential ratios, or the stated short-interval average-temperature approximation.']),
 'gas':('An ideal-gas question connects pressure, volume and temperature.',['Convert temperature to kelvin and volume to m³.','Use PV = nRT for pressure, or √(3RT/M) for rms speed.','Use M in kg/mol and distinguish pressure ∝ T from speed ∝ √T.']),
 'degrees':('The gas type or its active degrees of freedom is specified.',['Count the active quadratic energy terms f.','Use Cᵥ = fR/2 and Cₚ = Cᵥ + R for molar capacities.','Use γ = Cₚ/Cᵥ; only include vibration if the question activates it.']),
 'pv':('A gas follows a specified path on a P–V diagram.',['Identify the path before choosing a work formula.','Calculate work by gas as the signed area under the path.','Use Q = ΔU + W with one consistent sign convention.']),
 'engine':('A heat engine operates between hot and cold reservoirs.',['Convert both reservoir temperatures to kelvin.','Use η_C = 1 − T_c/T_h only for the reversible limit.','Relate actual work and heat with η = W/Q_h and Q_c = Q_h − W.']),
 'mixing':('Rigid insulated vessels of the same ideal gas are connected.',['Treat both vessels as one system: external heat and work are zero.','Conserve total internal energy to find the final temperature.','Use total moles and total volume in the final ideal-gas equation.'])
}
for section_labs in LABS.values():
    for entry in section_labs:
        entry['use_when'],entry['problem_steps']=PROBLEM_GUIDES[entry['key']]
