"""Render authored lessons and syllabus into static pages. No network required."""
import html, json, pathlib, re, sys
ROOT=pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from content.physics_lessons import CHAPTERS
from content.exemplar_practice import QUESTIONS
from content.challenge_practice import QUESTIONS as CHALLENGES
SITE=ROOT/'site'
syllabus=json.loads((ROOT/'content/syllabus.json').read_text())
escape=html.escape
banks=['q-test05','q-test06','q-solids','q-fluids-extra','q-completion','q-class11']
base=(SITE/'solids.html').read_text().split('<head>')[1].split('</head>')[0]
base=base[:base.index('<script')]
base=re.sub(r'<title>.*?</title>','<title>{title}</title>',base)
head=base+'<script src="assets/catalog.js"></script>\n<script src="assets/site.js"></script>\n'+''.join(f'<script src="assets/{b}.js"></script>\n' for b in banks)+'<script src="https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-svg-full.js" defer></script>\n'
def page(name,key,title,body,toc=False,scripts=''):
    (SITE/name).write_text('<!doctype html>\n<html lang="en"><head>'+head.replace('{title}',escape(title))+'</head>\n'+f'<body class="ch-mechanics" data-page="{key}"><div class="frame'+(' with-toc' if toc else '')+'">'+('<aside class="toc" aria-label="Sections"></aside>' if toc else '')+'<main class="content">'+body+'<footer class="footer">Class 11 Physics · Read the assumptions, check the units, and explain the result. Progress is saved in this browser.</footer></main></div>'+scripts+'</body></html>\n')
def hero(eyebrow,title,intro):
    return f'<header class="hero"><span class="eyebrow">{eyebrow}</span><h1>{escape(title)}</h1><p class="lede">{intro}</p></header>'
def formula(s):
    return '<div class="formula"><div class="f-title">'+escape(s['title'])+'</div><div class="f-main">\\[ '+s['formula']+' \\]</div><div class="f-where"><strong>Symbols and assumptions:</strong> '+s['symbols']+'</div></div>'
old={}
engine=(SITE/'assets/site.js').read_text()
for k,f,label in [('solids','solids.html','Mechanical Properties of Solids'),('fluids1','fluids-1.html','Fluids I · Pressure & Flow'),('fluids2','fluids-2.html','Fluids II · Viscosity & Surface Tension')]:
    text=(SITE/f).read_text()
    old[k]=dict(key=k,page=f,label=label,volume=3,sections=re.findall(r'<section\b[^>]*\bid="([^"]+)"',text))
new={c['key']:dict(key=c['key'],page=c['key']+'.html',label=c['title'],volume=c['volume'],sections=[s['id'] for s in c['sections']]) for c in CHAPTERS}
ordered=[(new|old)[key] for v in syllabus['physics'] for row in v['chapters'] for key in row[2:]]
topics={s['id']:dict(label=s['title'],page=c['key']+'.html') for c in CHAPTERS for s in c['sections']}
(SITE/'assets/catalog.js').write_text('/* Generated by scripts/render_physics.py */\nwindow.PHYSICS_CATALOG = '+json.dumps(ordered,ensure_ascii=False)+';\nwindow.PHYSICS_TOPICS = '+json.dumps(topics,ensure_ascii=False)+';\n')
questions=[]
for chapter_index,c in enumerate(CHAPTERS):
    key=c['key']
    body=hero(f'Class 11 · Coaching volume {c["volume"]} · module pp. {c["module_pages"]}',c['title'],c['intro'])
    body+='<div class="row"><a class="btn" href="chapters.html">← All chapters</a><a class="btn" href="practice.html?chapter='+key+'">Practise this chapter →</a></div>'
    if c['ncert']:
        part='1' if c['ncert']<=7 else '2'
        num=c['ncert'] if part=='1' else c['ncert']-7
        url=f'https://ncert.nic.in/textbook/pdf/keph{part}{num:02}.pdf'
        body+='<p class="small muted">Textbook alignment: <a href="'+url+'">NCERT Class 11 Physics · chapter '+str(c['ncert'])+'</a>. Coaching order and separate foundation modules follow your uploaded index.</p>'
    for i,s in enumerate(c['sections'],1):
        assert len(s['options'])==4 and 0<=s['answer']<4
        offset=sum(ord(ch) for ch in s['id'])%4
        options=s['options'][offset:]+s['options'][:offset]
        question=dict(id='c11-'+s['id'],src='c11',qno=f'{key} · {i}',topic=s['id'],type='concept' if not any(ch.isdigit() for ch in s['question']) else 'numerical',q=s['question'],opts=options,ans=(s['answer']-offset)%4,sol='<p>'+s['explanation']+'</p>')
        questions.append(question)
        body+=f'<section id="{s["id"]}" data-num="{i}" data-toc="{escape(s["title"],quote=True)}"><div class="sec-head"><span class="num">{i} <span class="level core">Core</span></span><h2>{escape(s["title"])}</h2></div><div class="prose"><p>{s["intro"]}</p><p>{s["reasoning"]}</p></div>'+formula(s)
        body+='<div class="callout trap"><span class="label">Watch the assumption</span><p>'+s['trap']+'</p></div>'
        body+='<div class="eg"><div class="eg-q"><span class="eg-tag">Worked example</span><p>'+s['example']+'</p></div><details><summary>Show solution</summary><div class="eg-a"><p>'+s['solution']+'</p></div></details></div>'
        if s['id'] == {'units':'units-propagation','vectors':'vectors-components','linear':'linear-graphs','plane':'plane-projectiles','work':'work-theorem','rotation':'rotation-momentum','gravitation':'gravitation-variation','oscillations':'oscillations-phase','waves':'waves-travelling','thermal-properties':'thermal-properties-conduction','kinetic-theory':'kinetic-theory-speeds','thermodynamics':'thermodynamics-isothermal'}.get(key):
            body+=f'<figure class="sim concept-model" data-model="{key}"><div class="sim-head"><span class="tag">Explore</span><h4>Change an input and explain the result</h4></div><div class="model-content"></div></figure>'
        body+=f'<div class="quiz" data-topic="{s["id"]}" data-limit="2"><h3>Check the idea</h3></div></section>'
    body+='<div class="callout tip"><span class="label">Chapter check</span><p>Explain each formula’s symbols and conditions without looking. Solve the examples before revealing their steps, then use <a href="practice.html?chapter='+key+'">chapter practice</a> to check what needs revision.</p></div>'
    page(key+'.html',key,c['title'],body,True,'<script src="assets/sims-class11.js"></script>')
questions+=CHALLENGES+QUESTIONS
(SITE/'assets/q-class11.js').write_text('/* Original concept checks + reviewed NCERT Exemplar adaptations. */\nwindow.QBANK = window.QBANK || [];\nwindow.QBANK.push(...'+json.dumps(questions,ensure_ascii=False,indent=2)+');\n')
# Make data loading identical on every existing learning page, preserving old IDs.
for f in ['index.html','solids.html','fluids-1.html','fluids-2.html','practice.html','revise.html']:
    text=(SITE/f).read_text()
    if 'assets/catalog.js' not in text:
        text=text.replace('<script src="assets/site.js">','<script src="assets/catalog.js"></script>\n<script src="assets/site.js">')
    if 'assets/q-class11.js' not in text:
        text=text.replace('<script src="assets/q-completion.js"></script>','<script src="assets/q-completion.js"></script>\n<script src="assets/q-class11.js"></script>')
        if f=='revise.html':
            text=text.replace('<script src="assets/site.js"></script>','<script src="assets/site.js"></script>\n'+''.join(f'<script src="assets/{b}.js"></script>\n' for b in banks))
    (SITE/f).write_text(text)
body=hero('Your uploaded sequence','Physics chapters','Work through four volumes in order, or return to a section you need. Fluids keeps its two-part layout; maths, vectors and friction remain separate coaching modules.')
for vol in syllabus['physics']:
    body+=f'<section id="volume-{vol["volume"]}"><h2>Volume {vol["volume"]}</h2><div class="grid-cards">'
    for row in vol['chapters']:
        for k in row[2:]:
            c=(new|old)[k]
            body+=f'<article class="card study-card" data-study-chapter="{k}"><span class="card-k">Module pp. {row[1]}</span><h3><a href="{c["page"]}">{escape(c["label"])}</a></h3><p data-study-summary></p><progress data-study-meter max="{len(c["sections"])}" value="0" aria-label="Sections studied"></progress><p class="small" data-practice-summary></p><a data-continue-study></a><p class="small"><a href="practice.html?chapter={k}">Chapter practice</a></p></article>'
    body+='</div></section>'
body+='<p><a href="syllabus.html">View the organised syllabus and source notes →</a></p>'
page('chapters.html','chapters','Physics chapters',body)
body=hero('Syllabus library','Organised syllabus','The uploaded contents pages cover Class 11: four physics volumes, three chemistry volumes and five biology units. This catalogue transcribes those books; use an official exam notice to establish current examinable scope.')
body+='<p>Images remain organised locally under <code>papers/syllabus/</code>. Their original filenames and checksums are preserved in the file manifest. One exact chemistry-volume-3 duplicate is retained separately. Physics lessons follow the uploaded chapter order.</p>'
for subject in ['physics','chemistry','biology']:
    body+=f'<section id="{subject}"><h2>{subject.title()}</h2>'
    for v in syllabus[subject]:
        title='Volume '+str(v['volume']) if 'volume' in v else 'Unit '+v['unit']
        body+='<h3>'+escape(title)+'</h3><div class="table-wrap"><table><thead><tr><th>Chapter</th><th>'+('Starts on p.' if subject=='biology' else 'Module pages')+'</th></tr></thead><tbody>'
        for row in v['chapters']:
            label=escape(row[0])
            if subject=='physics':
                label=' · '.join(f'<a href="{(new|old)[k]["page"]}">{escape((new|old)[k]["label"])}</a>' for k in row[2:])
            body+='<tr><td>'+label+'</td><td>'+str(row[1])+'</td></tr>'
        body+='</tbody></table></div>'
    body+='</section>'
body+='<section id="sources"><h2>Practice sources and review</h2><p>Original concept checks are labelled “Original NEET-style”. The source collector indexed question identifiers from the 14 official NCERT Exemplar PDFs. Selected patterns were rewritten with independent solutions and labelled “Adapted NCERT Exemplar”; they are not claimed to be NEET past-year questions.</p><p>Selection favours useful misconceptions, reasoning and numerical variety. The full collected collections are not automatically imported: source solutions can contain errors. For example, a descending lift above ground that slows has positive position, negative velocity and positive acceleration with an upward-positive axis.</p><ul>'
for source in json.loads((ROOT/'content/exemplar_sources.json').read_text()):
    body+='<li><a href="'+source['url']+'">NCERT Exemplar · '+escape(source['title'])+'</a></li>'
body+='</ul></section>'
page('syllabus.html','syllabus','Organised syllabus',body)
body=hero('Class 11 · revision','Formula reference','Read the symbols and limits alongside each relationship. Follow a chapter link if you cannot explain why the formula applies.')
body+='<div class="callout tip"><span class="label">Existing detailed reference</span><p><a href="revise.html">Solids and Fluids: formulas, ratio shortcuts and traps →</a></p></div>'
for meta in ordered:
    key=meta['key']
    body+='<section id="revision-'+key+'"><h2><a href="'+meta['page']+'">'+escape(meta['label'])+'</a></h2>'
    c=next((c for c in CHAPTERS if c['key']==key),None)
    if c:
        for entry in c['sections']:
            body+='<p class="small"><a href="'+meta['page']+'#'+entry['id']+'">Explanation and example →</a></p>'+formula(entry)
    else:
        text=(SITE/meta['page']).read_text()
        for match in re.finditer(r'<div class="formula">',text):
            depth=0
            for token in re.finditer(r'<div\b[^>]*>|</div>',text[match.start():]):
                depth+= -1 if token.group().startswith('</') else 1
                if depth==0:
                    body+=text[match.start():match.start()+token.end()]
                    break
    body+='</section>'
page('formula-sheet.html','revise','Class 11 formula reference',body,True)
# Homepage has its own layout; lesson generation must preserve its design.
volume_titles={1:'Foundations & Motion',2:'Forces, Energy & Rotation',3:'Gravity, Materials & Oscillations',4:'Waves & Thermal Physics'}
volume_cards=''
for vol in syllabus['physics']:
    number=vol['volume']
    volume_cards+=f'<article class="card home-volume" style="--c: var(--{["indigo","coral","water","plum"][number-1]})"><span class="card-k">Volume {number}</span><h3>{volume_titles[number]}</h3><ul>'
    for row in vol['chapters']:
        for key in row[2:]:
            meta=(new|old)[key]
            volume_cards+=f'<li><a href="{meta["page"]}">{escape(meta["label"])}</a></li>'
    volume_cards+='</ul></article>'
body=(SITE/'_home-body.html').read_text().replace('{{VOLUME_CARDS}}',volume_cards)
page('index.html','home','NEET Physics Notes',body)
text=(SITE/'index.html').read_text().replace('class="ch-mechanics" data-page="home"','class="ch-home" data-page="home"')
(SITE/'index.html').write_text(text)
# Local index and a tracked public audit describe the source image organisation.
md=['# Uploaded Class 11 syllabus','',syllabus['scope'],'','Original images are preserved by filename mapping and SHA-256 in file-manifest.json. One exact chemistry volume 3 duplicate is in duplicates/.','']
for subject in ['physics','chemistry','biology']:
    md+=['## '+subject.title(),'']
    for v in syllabus[subject]:
        md+=['### '+('Volume '+str(v['volume']) if 'volume' in v else v['unit']),'']
        md += [f'- {r[0]} — '+('starts p. ' if subject=='biology' else 'pp. ')+str(r[1]) for r in v['chapters']]
        md+=['']
(ROOT/'papers/syllabus').mkdir(parents=True,exist_ok=True)
(ROOT/'papers/syllabus/README.md').write_text('\n'.join(md))
(ROOT/'docs/syllabus-catalogue.md').write_text('\n'.join(md)+'\n\nPublic catalogue: site/syllabus.html. Physics lessons: site/chapters.html. Original source images are not redistributed.\n')
print(f'Rendered {len(CHAPTERS)} new chapters, {sum(len(c["sections"]) for c in CHAPTERS)} new sections and {len(questions)} new practice questions.')
